dependencies:
        - boost
        - ccache
        - clang
        - clangxx
        - cmake
        - docutils
        - doxygen
        - eigen
        - fftw
        - gfortran
        - ipykernel
        - lark-parser
        - libclang
        - libcxx
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - nanobind
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - setuptools
        - sphinx=8
        - sphinx-copybutton
        - sphinx-favicon
        - sphinx-rtd-theme=3
        - sphinxcontrib-jquery
        - sphinxcontrib-mermaid>=1.0.0
        - tqdm
        - xarray
        - zlib
channels:
        - conda-forge
        - nodefaults
