dependencies:
        - binutils
        - boost
        - ccache
        - clang
        - clangxx
        - cmake
        - doxygen
        - docutils
        - eigen
        - fftw
        - gcc
        - gfortran
        - gmp
        - gxx
        - ipykernel
        - lark-parser
        - libclang
        - libcxx
        - llvm-openmp
        - nanobind
        - nbsphinx
        - matplotlib
        - netcdf4
        - ninja
        - numpy>=2
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - sphinx=8
        - sphinx-favicon
        - sphinx-rtd-theme=3
        - sphinxcontrib-jquery
        - sphinxcontrib-mermaid>=1.0.0
        - xarray
        - zlib
channels:
        - conda-forge
