dependencies:
        - boost
        - ccache
        - clang
        - clangxx
        - cmake
        - docutils
        - doxygen
        - eigen
        - fftw
        - gfortran
        - ipykernel
        - lark-parser
        - libclang
        - libcxx
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - nanobind
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - pkg-config
        - pytest
        - python-build
        - requests
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinxcontrib-mermaid
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
