dependencies:
        - boost
        - make
        - cmake
        - docutils
        - eigen
        - fftw
        - ipykernel
        - lark-parser
        - libcxx
        - matplotlib
        - nanobind
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - openblas
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - sphinx=8
        - sphinx-favicon
        - sphinx-rtd-theme=3
        - sphinxcontrib-jquery
        - sphinxcontrib-mermaid>=1.0.0
        - tqdm
        - xarray
        - zlib
channels:
        - conda-forge
        - nodefaults
