dependencies:
        - binutils
        - boost
        - ccache
        - clang
        - clangxx
        - cmake
        - doxygen
        - docutils
        - eigen
        - fftw
        - gcc
        - gfortran
        - gmp
        - gxx
        - lark-parser
        - libclang
        - libcxx
        - llvm-openmp
        - nanobind
        - nbsphinx
        - matplotlib
        - netcdf4
        - ninja
        - numpy>=2
        - pkg-config
        - pytest
        - python-build
        - requests
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinx_rtd_theme
        - sphinxcontrib-mermaid
        - xarray
        - zlib
channels:
        - conda-forge
