dependencies:
        - boost
        - make
        - cmake
        - docutils
        - eigen
        - fftw
        - ipykernel
        - lark-parser
        - libcxx
        - matplotlib
        - nanobind
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - openblas
        - pkg-config
        - pytest>=7
        - python-build
        - requests
        - scipy
        - sphinx<8.1.0
        - sphinx-favicon
        - sphinxcontrib-jquery
        - sphinxcontrib-mermaid
        - xarray
        - zlib
        - pip:
          - sphinx-rtd-theme
channels:
        - conda-forge
