dependencies:
        - boost
        - build
        - ccache
        - clang=16.*
        - clangxx
        - cmake
        - docutils
        - doxygen
        - eigen
        - gfortran
        - glew
        - glfw
        - lark-parser
        - libclang=16.*
        - libcxx
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - netcdf4
        - ninja
        - numpy
        - pkg-config
        - pybind11
        - pytest
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinxcontrib-mermaid
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
