name: pyarts-dev
dependencies:
        - python=3.10
        - build
        - ccache
        - clang=16.*
        - clangxx
        - cmake
        - docutils
        - gfortran
        - glew
        - glfw
        - lark-parser
        - libclang=16.*
        - libcxx
        - libmicrohttpd
        - llvm-openmp
        - matplotlib
        - netcdf4
        - numpy
        - pkg-config
        - pybind11
        - pytest
        - scipy
        - sphinx>=6
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
