dependencies:
        - boost
        - build
        - make
        - cmake
        - docutils
        - eigen
        - glew
        - glfw
        - lark-parser
        - libcxx
        - matplotlib
        - nanobind
        - netcdf4
        - ninja
        - numpy>=2
        - openblas
        - pkg-config
        - pybind11
        - pytest
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinxcontrib-mermaid
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
