dependencies:
        - boost
        - make
        - cmake
        - docutils
        - eigen
        - fftw
        - lark-parser
        - libcxx
        - matplotlib
        - nanobind>=2.1.0
        - nbsphinx
        - netcdf4
        - ninja
        - numpy>=2
        - openblas
        - pkg-config
        - pytest
        - python-build
        - requests
        - scipy
        - sphinx
        - sphinx-favicon
        - sphinxcontrib-mermaid
        - sphinx_rtd_theme
        - xarray
        - zlib
channels:
        - conda-forge
